// flow-typed signature: 2ab6aca5159a92e2aaa174d2f6a23cdf
// flow-typed version: <<STUB>>/howler_v2.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'howler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "howler" {
  declare interface Howl {
    constructor({|
      src: string | Array<string>,
      distanceModel?: "exponential" | "inverse" | "linear",
      loop?: boolean,
      preload?: boolean,
      rolloffFactor?: number,
      volume?: number
    |}): void;

    pause(): void;

    play(): void;

    pos(x: number, y: number, z: number): void;

    stop(): void;
  }

  declare class Howler {
    pos(x: number, y: number, z: number): void;
  }

  declare module.exports: {|
    Howl: Howl,
    Howler: Howler
  |};
}
