// flow-typed signature: 0968b55b37702c0a270828210a61539a
// flow-typed version: <<STUB>>/javascript-state-machine_v3.1.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-state-machine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "javascript-state-machine" {
  declare type TransitionsConfiguration<States, Transitions> = Array<{|
    name: $Keys<Transitions>,
    from: States,
    to: States
  |}>;

  declare type HelperMethods<States, Transitions> = {|
    allStates(): Array<States>,

    allTransitions(): Array<$Keys<Transitions>>,

    can($Keys<Transitions>): boolean,

    cannot($Keys<Transitions>): boolean,

    is(States): boolean,

    transitions(): Array<$Keys<Transitions>>
  |};

  declare type StateMachineClass<States, Transitions> = {|
    ...$Exact<Transitions>,
    ...$Exact<HelperMethods<States, Transitions>>,
    ...$Exact<{|
      state: States
    |}>
  |};

  declare type StateMachineConfiguration<States, Transitions, Methods> = {|
    init: States,
    transitions: TransitionsConfiguration<States, Transitions>,
    methods: Methods
  |};

  declare class StateMachineConstructor<States, Transitions> {
    constructor(): StateMachineClass<States, Transitions>;
  }

  declare class StateMachine<States, Transitions, Methods> {
    static factory<TStates, TTransitions, TMethods>(
      StateMachineConfiguration<TStates, TTransitions, TMethods>
    ): Class<StateMachineConstructor<TStates, TTransitions, TMethods>>;

    constructor(
      StateMachineConfiguration<States, Transitions, Methods>
    ): StateMachineClass<States, Transitions>;
  }

  declare module.exports: typeof StateMachine;
}
