// flow-typed signature: fbb2e9188488680147415e110fcf430a
// flow-typed version: <<STUB>>/jsonrpc-lite_v^2.0.7/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonrpc-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "jsonrpc-lite" {
  declare export class JsonRpcError {
    constructor(message: string, code: number): void;
  }

  declare export type JsonRpcErrorResponse = JsonRpcResponse & {|
    +error: {|
      +code: number,
      +message: string,
    |},
  |};

  declare export type JsonRpcRequest<Method: string, Params> = JsonRpcResponse & {|
    +method: Method,
    +params: Params,
  |};

  declare export type JsonRpcResponse = {|
    +id: string,
    +jsonrpc: "2.0",
  |};

  declare export type JsonRpcSuccessResponse<T: Object> = JsonRpcResponse & {|
    +result: T,
  |};

  declare export default {|
    JsonRpcError: Class<JsonRpcError>,

    error<T>(id: string, JsonRpcError): JsonRpcErrorResponse,

    request<Method: string, Params: Object>(id: string, Method, data: Params): JsonRpcRequest<Method, Params>,

    success<T: Object>(id: string, data: T): JsonRpcSuccessResponse<T>,
  |};
}
