// flow-typed signature: 53d5948ae6fe2fe6dbfe68b587c4e948
// flow-typed version: <<STUB>>/pathfinding_v0.4.18/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pathfinding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "pathfinding" {
  declare module.exports: any;
}
