// flow-typed signature: 53d5948ae6fe2fe6dbfe68b587c4e948
// flow-typed version: <<STUB>>/pathfinding_v0.4.18/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pathfinding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "pathfinding" {
  declare type Path = $ReadOnlyArray<[number, number]>;

  declare interface Finder {
    findPath(number, number, number, number, Grid): Path;
  }

  declare export interface BestFirstFinder extends Finder {
    constructor(options?: {|
      diagonalMovement?: 1 | 2 | 3 | 4,
    |}): void;
  }

  declare export interface Grid {
    constructor($ReadOnlyArray<$ReadOnlyArray<number>>): void;
  }

  declare export class DiagonalMovement {
    static +Always: 1;
    static +Never: 2;
    static +IfAtMostOneObstacle: 3;
    static +OnlyWhenNoObstacles: 4;
  }

  declare export class Util {
    static compressPath(Path): Path;
  }
}
