// flow-typed signature: ffa451e40454b6bcfbc1f106cb0092c9
// flow-typed version: <<STUB>>/raf_v3.4.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "raf" {
  declare type RafCallback = () => any;
  declare type RafId = number;

  declare type raf = {
    (RafCallback): RafId,
    cancel(RafId): void
  };

  declare module.exports: raf;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
// Filename aliases
declare module "raf/index" {
  declare module.exports: $Exports<"raf">;
}
declare module "raf/index.js" {
  declare module.exports: $Exports<"raf">;
}
