// flow-typed signature: f9dfdb4bff252660a3e09b4441c5ee6d
// flow-typed version: <<STUB>>/resize-observer-polyfill_v1.5.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resize-observer-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "resize-observer-polyfill" {
  declare module.exports: ResizeObserver;
}
