// flow-typed signature: ad82709371011e9bbacc6d4d3e8e3c1d

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "twig" {
  declare type TwigRendererData = {
    [string]: any
  };

  declare type TwigRenderer = {|
    renderAsync: (data: TwigRendererData) => Promise<string>
  |};

  declare type Twig = {|
    twig: ({|
      data: string,
      rethrow: boolean,
      strict_variables: boolean
    |}) => TwigRenderer
  |};

  declare module.exports: Twig;
}
