// flow-typed signature: c0b700b91cc1133633800106a018281c
// flow-typed version: <<STUB>>/@tweenjs/tween.js_v^17/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tweenjs/tween.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@tweenjs/tween.js" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@tweenjs/tween.js/benchmarks/additionWithoutStart" {
  declare module.exports: any;
}

declare module "@tweenjs/tween.js/benchmarks/additionWithStart" {
  declare module.exports: any;
}

declare module "@tweenjs/tween.js/benchmarks/additionWithUpdate" {
  declare module.exports: any;
}

declare module "@tweenjs/tween.js/benchmarks/updateMany" {
  declare module.exports: any;
}

declare module "@tweenjs/tween.js/src/Tween" {
  declare module.exports: any;
}

declare module "@tweenjs/tween.js/src/TweenThree" {
  declare module.exports: any;
}

// Filename aliases
declare module "@tweenjs/tween.js/benchmarks/additionWithoutStart.js" {
  declare module.exports: $Exports<
    "@tweenjs/tween.js/benchmarks/additionWithoutStart"
  >;
}
declare module "@tweenjs/tween.js/benchmarks/additionWithStart.js" {
  declare module.exports: $Exports<
    "@tweenjs/tween.js/benchmarks/additionWithStart"
  >;
}
declare module "@tweenjs/tween.js/benchmarks/additionWithUpdate.js" {
  declare module.exports: $Exports<
    "@tweenjs/tween.js/benchmarks/additionWithUpdate"
  >;
}
declare module "@tweenjs/tween.js/benchmarks/updateMany.js" {
  declare module.exports: $Exports<"@tweenjs/tween.js/benchmarks/updateMany">;
}
declare module "@tweenjs/tween.js/src/Tween.js" {
  declare module.exports: $Exports<"@tweenjs/tween.js/src/Tween">;
}
declare module "@tweenjs/tween.js/src/TweenThree.js" {
  declare module.exports: $Exports<"@tweenjs/tween.js/src/TweenThree">;
}
